package com.githubrepos.app.data_implementation.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class RepoEntity(
    @PrimaryKey(autoGenerate = false) var id: Int = -1,
    var nodeId: String? = null,
    var name: String? = null,
    var fullName: String? = null,
    var private: Boolean? = null,
    var owner: OwnerEntity? = null,
    var htmlUrl: String? = null,
    var description: String? = null,
    var fork: Boolean? = null,
    var url: String? = null,
    var forksUrl: String? = null,
    var forksCount: Int? = null,
    var keysUrl: String? = null,
    var collaboratorsUrl: String? = null,
    var teamsUrl: String? = null,
    var hooksUrl: String? = null,
    var issueEventsUrl: String? = null,
    var eventsUrl: String? = null,
    var assigneesUrl: String? = null,
    var branchesUrl: String? = null,
    var tagsUrl: String? = null,
    var blobsUrl: String? = null,
    var gitTagsUrl: String? = null,
    var gitRefsUrl: String? = null,
    var treesUrl: String? = null,
    var statusesUrl: String? = null,
    var languagesUrl: String? = null,
    var language: String? = null,
    var stargazersUrl: String? = null,
    var stargazersCount: Int? = null,
    var contributorsUrl: String? = null,
    var subscribersUrl: String? = null,
    var subscriptionUrl: String? = null,
    var commitsUrl: String? = null,
    var gitCommitsUrl: String? = null,
    var commentsUrl: String? = null,
    var issueCommentUrl: String? = null,
    var contentsUrl: String? = null,
    var compareUrl: String? = null,
    var mergesUrl: String? = null,
    var archiveUrl: String? = null,
    var downloadsUrl: String? = null,
    var issuesUrl: String? = null,
    var pullsUrl: String? = null,
    var milestonesUrl: String? = null,
    var notificationsUrl: String? = null,
    var labelsUrl: String? = null,
    var releasesUrl: String? = null,
    var deploymentsUrl: String? = null
)